#!/usr/bin/env python3
"""README "(n,a)": the v1 recipe vs default TALYS (our engine = TENDL's no-data recipe) on the three fresh data sets,
each registered before it was read. rms of log10(model / data) per set; the change is v1 / default - 1.
Helium production also by mass, with HEPROD's definition (natural targets count as A > 70 when Z > 30).
    python scripts/release/score_na_v1.py docs/release/exam/na_v1_rows.parquet OUT.md
Ported from the development tree: docs/release/na_v1/score_hybrid.py, score_heprod.py."""
import sys, numpy as np, pandas as pd
r = pd.read_parquet(sys.argv[1]); rms = lambda x: float(np.sqrt(np.mean(np.square(x))))
out = ["# (n,a) v1 recipe vs default TALYS on fresh data (regenerated by scripts/release/score_na_v1.py)", "",
       "| set | points / targets | default TALYS | v1 | change |", "|---|---|---|---|---|"]
def line(nm, s):
    d, v = rms(np.log10(s.default_mb / s.data_mb)), rms(np.log10(s.v1_mb / s.data_mb))
    out.append(f"| {nm} | {len(s)} / {(s.Z * 1000 + s.A).nunique()} | {d:.4f} | {v:.4f} | {100 * (v / d - 1):+.0f} % |")
for nm in ("isomer/ground/total", "helium production", "never-read (M)/M+"):
    s = r[r.set == nm]; line(nm, s)
    if nm == "helium production": line("  helium production, A > 70", s[(s.A > 70) | ((s.A == 0) & (s.Z > 30))])
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
