#!/usr/bin/env python3
"""README "The engine": the TALYS port vs stock TALYS-2.x at identical settings (strength 9, ldmodel 1) on the measured rows of
the channel scoreboard: rms of log10(model / data) per channel and the row-level difference.
    python scripts/release/score_stock.py docs/release/exam/stock_rows.parquet OUT.md
Ported from the development tree: scripts/channels/score_stock_control.py (rows as published; library columns removed)."""
import sys, numpy as np, pandas as pd
R = pd.read_parquet(sys.argv[1]); R = R[R.published_mask]; rms = lambda x: float(np.sqrt(np.mean(np.square(x))))
out = ["# Engine vs stock TALYS (regenerated by scripts/release/score_stock.py)", "", "| channel | rows (nuclides) | engine | stock TALYS | engine - stock | median / 99th pct abs log10(engine/stock) |", "|---|---|---|---|---|---|"]
for ch in ("total", "elastic", "inelastic", "n2n", "np", "na"):
    g = R[R.channel == ch]; le, ls = np.log10(g.engine_s9l1 / g.data), np.log10(g.stock_s9l1 / g.data); d = np.abs(le - ls)
    out.append(f"| {ch} | {len(g)} ({g.nuc.nunique()}) | {rms(le):.4f} | {rms(ls):.4f} | {rms(le) - rms(ls):+.4f} | {np.median(d):.4f} / {np.quantile(d, .99):.3f} |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
