#!/usr/bin/env python3
"""README "Uncertainties", capture blind tiers: coverage of the shipped MEASURED-rule 68 / 95 % intervals on held-out rows
(leave-nucleus-out; rows from datasets flagged by curation rule P removed).
    python scripts/release/score_tiers.py docs/release/exam/tier_rows.parquet OUT.md
Ported from the development tree: audit2/rescore_c3_c6.py (C6)."""
import sys, numpy as np, pandas as pd
r = pd.read_parquet(sys.argv[1]); m = r.scored & ~r.ruleP_flagged; a = np.abs(r.err[m])
out = ["# Blind-tier interval coverage (regenerated by scripts/release/score_tiers.py)", "", "| rows | coverage 68 % | coverage 95 % |", "|---|---|---|",
       f"| {int(m.sum())} | {100 * np.mean(a < r.h68[m]):.1f} | {100 * np.mean(a < r.h95[m]):.1f} |"]
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
