#!/usr/bin/env python3
"""README "Library-value-free model: the registered vault read": the shipped library-value-free model (INDEP2) vs the release
candidate (RC, which carried an ENDF/B-VII.1 prior blend) on the reserved folds 6-7, read once. Both trained on folds 0-5 in the
same run (3 seeds x 5 members); rule-P-touched cells removed; Z <= 82. Paired nucleus bootstrap 95 % CI, 10,000 draws, seed 20260923.
    python scripts/release/score_vault.py docs/release/exam/vault_rows.parquet OUT.md
Ported from the development tree: docs/release/indep_fix2/score2.py."""
import sys, numpy as np, pandas as pd
V = pd.read_parquet(sys.argv[1]); rms = lambda e: float(np.sqrt(np.mean(np.asarray(e) ** 2)))
def cmp(a, q, n, seed=20260923, draws=10000):
    u, inv = np.unique(n, return_inverse=True); SA, SB, k = np.bincount(inv, a ** 2), np.bincount(inv, q ** 2), np.bincount(inv).astype(float)
    w = np.random.default_rng(seed).multinomial(len(u), np.full(len(u), 1 / len(u)), size=draws).astype(float)
    d = np.sqrt(w @ SA / (w @ k)) - np.sqrt(w @ SB / (w @ k)); lo, hi = np.percentile(d, [2.5, 97.5]); return f"{rms(a) - rms(q):+.4f} [{lo:+.4f}, {hi:+.4f}]"
out = ["# Vault read, folds 6-7 (regenerated by scripts/release/score_vault.py)", "",
       "| D0 | cells (nuclei) | RC | shipped (INDEP2) | shipped - RC [95 % CI] | coverage 68 / 95 %, RC -> shipped | shipped - no-data recipe [95 % CI] (recipe rms) |", "|---|---|---|---|---|---|---|"]
for em, nm in (("d0free", "withheld"), ("d0ass", "assisted")):
    s = V[V.exam == em]; n = s.nuclide_id.to_numpy(); a, b, r = s.err_rc.to_numpy(), s.err_indep2.to_numpy(), s.err_recipe.to_numpy()
    cr = f"{100 * np.mean(np.abs(a) < s.h68_rc):.1f} / {100 * np.mean(np.abs(a) < s.h95_rc):.1f}"; ci = f"{100 * np.mean(np.abs(b) < s.h68_indep2):.1f} / {100 * np.mean(np.abs(b) < s.h95_indep2):.1f}"
    m = np.isfinite(r)
    out.append(f"| {nm} | {len(s)} ({len(np.unique(n))}) | {rms(a):.4f} | {rms(b):.4f} | {cmp(b, a, n)} | {cr} -> {ci} | {cmp(b[m], r[m], n[m])} ({rms(r[m]):.4f}) |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
