#!/usr/bin/env python3
"""README "Capture on nuclei held out of the fit (blind)": regenerate the table from the frozen per-cell exam file.

    python scripts/release/score_capture_blind.py docs/release/exam/capture_blind_cells.parquet OUT.md

rms of log10(prediction / measurement); paired nucleus bootstrap 95 % CI, 10,000 draws, seed 20260923.
Targets: the curation-audited targets (`target_log10_P`, CURATION-AUDIT2 rule P) for the D0 rows, the well-measured row
and the precision cut, as published; the original targets for the STRIP row, as published by CAPFAR.
  D0 assisted / withheld : all folds, Z <= 82, cells where all four predictors and the audited target exist
  no structure (STRIP)   : DEV folds 0-5, Z <= 82, original targets (1,966 cells)
  well measured          : D0 assisted, audited trust >= 1
  precision cut          : D0 assisted, >= 3 pre-2012 series within x1.3, E < 10 MeV, cells NON-SMOKER also covers;
                           ratio ours / recipe with a nucleus bootstrap (seed 20260921)
Ported from the development tree: capture_d0free_exam.py, capture_farfield.py, audit2/rescore_c1.py, audit2/rescore_c3_c6.py.
"""
import sys
import numpy as np, pandas as pd

X = pd.read_parquet(sys.argv[1]); nid = X.nuclide_id.to_numpy(); Z = X.Z.to_numpy(); en = X.energy_ev.to_numpy()
rms = lambda e: float(np.sqrt(np.mean(e ** 2)))


def boot(a, q, n, seed=20260923, draws=10000, ratio=False):
    u, inv = np.unique(n, return_inverse=True); SA, SB, k = np.bincount(inv, a ** 2), np.bincount(inv, q ** 2), np.bincount(inv).astype(float)
    w = np.random.default_rng(seed).multinomial(len(u), np.full(len(u), 1 / len(u)), size=draws).astype(float)
    ra, rq = np.sqrt(w @ SA / (w @ k)), np.sqrt(w @ SB / (w @ k))
    if ratio:
        lo, hi = np.percentile(ra / rq, [2.5, 97.5]); return f"ratio {rms(a) / rms(q):.2f} [{lo:.2f}, {hi:.2f}]"
    lo, hi = np.percentile(ra - rq, [2.5, 97.5]); return f"{rms(a) - rms(q):+.4f} [{lo:+.4f}, {hi:+.4f}]"


def err(k, target): return X[f"pred_{k}"].to_numpy() - X[target].to_numpy()


eP = {k: err(k, "target_log10_P") for k in ("ours_d0free", "ours_d0assisted", "recipe_d0free", "recipe_d0assisted")}
eO = {k: err(k, "target_log10") for k in ("ours_strip", "recipe_strip")}
ok = (Z <= 82) & np.all([np.isfinite(v) for v in eP.values()], 0)
st = (Z <= 82) & np.isin(X.fold, range(6)) & np.isfinite(eO["ours_strip"]) & np.isfinite(eO["recipe_strip"])
tr = ok & (X.trust_P.to_numpy() >= 1)
pc = (Z <= 82) & (en < 1e7) & np.isfinite(eP["ours_d0assisted"]) & np.isfinite(eP["recipe_d0assisted"]) & X.nonsmoker_covers.to_numpy() & X.precision_P.to_numpy()
rows = [("structure data and its measured D0", ok, eP["ours_d0assisted"], eP["recipe_d0assisted"], {}),
        ("structure data, D0 withheld (headline)", ok, eP["ours_d0free"], eP["recipe_d0free"], {}),
        ("nothing (STRIP; DEV folds 0-5; original targets)", st, eO["ours_strip"], eO["recipe_strip"], {}),
        ("well-measured cells (trust >= 1), D0 assisted", tr, eP["ours_d0assisted"], eP["recipe_d0assisted"], {}),
        (">= 3 datasets within x1.3 (precision cut), D0 assisted", pc, eP["ours_d0assisted"], eP["recipe_d0assisted"], dict(seed=20260921, ratio=True))]
out = ["# Blind capture table (regenerated by scripts/release/score_capture_blind.py)", "",
       "| what the model knows about the held-out nucleus | cells (nuclei) | ours | TENDL's no-data recipe (our engine) | ours vs recipe [95 % CI] |", "|---|---|---|---|---|"]
for nm, m, a, q, kw in rows:
    ci = boot(a[m], q[m], nid[m], **kw)
    if kw.get("ratio"): ci = boot(a[m], q[m], nid[m]) + "; " + ci   # paired difference (seed 20260923) next to the published ratio
    out.append(f"| {nm} | {int(m.sum())} ({len(np.unique(nid[m]))}) | {rms(a[m]):.4f} | {rms(q[m]):.4f} | {ci} |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
