#!/usr/bin/env python3
"""README "Uncertainties", D0 withheld: coverage of the shipped INTERPOLATED 68 / 95 % interval by achieved chart distance d
(HOLE + HOLE-2 + SCATTER held-out rows, Z <= 83, hashed reserve nuclides excluded), nucleus bootstrap 95 % CI (2,000, seed 20260923).
    python scripts/release/score_interp_interval.py docs/release/exam/interp_interval_rows.parquet OUT.md
Ported from the development tree: scripts/release/terra/capture_scatter_score.py (table B2, SHIPPED column)."""
import sys, numpy as np, pandas as pd
R = pd.read_parquet(sys.argv[1]); e, h68, h95, nid = R.err.to_numpy(), R.h68.to_numpy(), R.h95.to_numpy(), R.nuclide_id.to_numpy()
d, f0, rsv = R.d.to_numpy(), R.d0free.to_numpy(), R.reserve.to_numpy()
def cov(m, draws=2000):
    c68, c95 = np.abs(e[m]) <= h68[m], np.abs(e[m]) <= h95[m]
    un, inv = np.unique(nid[m], return_inverse=True); n = np.bincount(inv).astype(float); s68, s95 = np.bincount(inv, c68), np.bincount(inv, c95)
    w = np.random.default_rng(20260923).multinomial(len(un), np.full(len(un), 1 / len(un)), size=draws).astype(float)
    q = lambda s: np.percentile(100 * (w @ s) / (w @ n), [2.5, 97.5]); return 100 * c68.mean(), 100 * c95.mean(), q(s68), q(s95), len(un)
out = ["# Shipped INTERPOLATED interval by distance (regenerated by scripts/release/score_interp_interval.py)", "",
       "| D0 | d | rows | nuclei | 68 / 95 % coverage [95 % CI] |", "|---|---|---|---|---|"]
for fl, nm in ((1, "withheld"), (0, "assisted")):
    for s, lo, up in (("1", 1, 1), ("2", 2, 2), ("3-4", 3, 4), ("5-6", 5, 6), ("7+", 7, 99)):
        m = (~rsv) & (f0 == fl) & (d >= lo) & (d <= up)
        if m.sum() == 0: continue
        a = cov(m); out.append(f"| {nm} | {s} | {int(m.sum())} | {a[4]} | {a[0]:.0f} / {a[1]:.0f} [{a[2][0]:.0f}-{a[2][1]:.0f} / {a[3][0]:.0f}-{a[3][1]:.0f}] |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
