#!/usr/bin/env python3
"""README "Clean retrain (2026-09-23)": the shipped model retrained without the 69 capture datasets flagged by curation rule P,
OLD vs CLEAN on the DEV exam (folds 0-5, Z <= 82, cells those datasets touched removed), D0 withheld and D0 assisted.
Paired nucleus bootstrap 95 % CI, 10,000 draws, seed 20260923.
    python scripts/release/score_clean_retrain.py docs/release/exam/clean_retrain_rows.parquet OUT.md
Ported from the development tree: docs/release/terra/retrain_clean/score_clean.py."""
import sys, numpy as np, pandas as pd
r = pd.read_parquet(sys.argv[1]); rms = lambda e: float(np.sqrt(np.mean(np.asarray(e) ** 2)))
def cmp(a, q, n, seed=20260923, draws=10000):
    u, inv = np.unique(n, return_inverse=True); SA, SB, k = np.bincount(inv, a ** 2), np.bincount(inv, q ** 2), np.bincount(inv).astype(float)
    w = np.random.default_rng(seed).multinomial(len(u), np.full(len(u), 1 / len(u)), size=draws).astype(float)
    d = np.sqrt(w @ SA / (w @ k)) - np.sqrt(w @ SB / (w @ k)); lo, hi = np.percentile(d, [2.5, 97.5]); return rms(a) - rms(q), lo, hi
out = ["# Clean retrain on the DEV exam (regenerated by scripts/release/score_clean_retrain.py)", "",
       "| emulation | cells (nuclei) | OLD | CLEAN | CLEAN - OLD [95 % CI] |", "|---|---|---|---|---|"]
for em, nm in (("d0free", "D0 withheld"), ("d0ass", "D0 assisted")):
    s = r[r.emulation == em]; n = s.nuclide_id.to_numpy(); a, b = s.err_old.to_numpy(), s.err_clean.to_numpy(); d, lo, hi = cmp(b, a, n)
    out.append(f"| {nm} | {len(s)} ({len(np.unique(n))}) | {rms(a):.4f} | {rms(b):.4f} | {d:+.4f} [{lo:+.4f}, {hi:+.4f}] |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
