#!/usr/bin/env python3
"""README (n,p) claims: the learned correction (frozen C3) vs our engine's TENDL no-data recipe (R0) on the registered fresh set,
and its Student-t intervals: cross-fitted on held-out elements (M1, 6 element groups) and descriptive on the fresh records.
    python scripts/release/score_np.py docs/release/exam OUT.md
Ported from the development tree: NP-CONFIRM scorer (terra_model.boot_diff, 2,000 draws, seed 20260923) and docs/release/terra/np_intervals.py."""
import json, sys
import numpy as np, pandas as pd
from scipy import stats
from scipy.optimize import minimize
D = sys.argv[1]; F = pd.read_parquet(D + "/np_fresh_rows.parquet"); R = pd.read_parquet(D + "/np_interval_rows.parquet"); P = json.load(open(D + "/np_interval_params.json"))
rms = lambda x: float(np.sqrt(np.mean(np.square(x))))
def boot_diff(a, b, nid, n=2000, seed=20260923):
    rng = np.random.default_rng(seed); u = np.unique(nid); idx = {q: np.where(nid == q)[0] for q in u}
    sa, sb = {q: np.sum(a[idx[q]] ** 2) for q in u}, {q: np.sum(b[idx[q]] ** 2) for q in u}; cnt = {q: len(idx[q]) for q in u}; out = []
    for _ in range(n):
        s = rng.choice(u, len(u)); N = sum(cnt[q] for q in s); out.append(np.sqrt(sum(sa[q] for q in s) / N) - np.sqrt(sum(sb[q] for q in s) / N))
    return rms(a) - rms(b), float(np.quantile(out, 0.025)), float(np.quantile(out, 0.975))
def sig0(p, dE): return np.sqrt(np.exp(p[0]) ** 2 + np.exp(p[1]) ** 2 * np.exp(-np.clip(dE, 0, None) / 2.0))
def sigma(p, dE, never): return sig0(p, dE) * np.exp(p[3] * never)
def cover(e, s, nu): return np.abs(e) <= stats.t.ppf(0.84134, nu) * s, np.abs(e) <= stats.t.ppf(0.975, nu) * s
def fit(e, dE, never):
    def nll(p):
        nu = 2.0 + np.exp(p[2]); s = sigma(p, dE, never); return -np.sum(stats.t.logpdf(e / s, nu) - np.log(s))
    return minimize(nll, [np.log(0.13), np.log(0.2), np.log(1.5), 0.0], method="Nelder-Mead", options=dict(maxiter=20000, xatol=1e-7, fatol=1e-9)).x
out = ["# (n,p) learned correction (regenerated by scripts/release/score_np.py)", "", "## Fresh set: frozen C3 vs our engine's no-data recipe", "",
       "| subset | records (nuclei) | ours | recipe | ours - recipe [95 % CI] |", "|---|---|---|---|---|"]
for nm, m in (("all", np.ones(len(F), bool)), ("9 nuclei never touched anywhere", F.nuclide_clean.to_numpy())):
    x = F[m]; d, lo, hi = boot_diff(x.err_pick.to_numpy(), x.err_R0.to_numpy(), x.nid.to_numpy())
    out.append(f"| {nm} | {len(x)} ({x.nid.nunique()}) | {rms(x.err_pick):.4f} | {rms(x.err_R0):.4f} | {d:+.4f} [{lo:+.4f}, {hi:+.4f}] |")
c68 = np.zeros(len(R), bool); c95 = np.zeros(len(R), bool)
for g in range(6):
    tr, te = (R.grp != g).to_numpy(), (R.grp == g).to_numpy(); p = fit(R.e[tr].to_numpy(), R.dE[tr].to_numpy(), R.never[tr].to_numpy())
    a, b = cover(R.e[te].to_numpy(), sigma(p, R.dE[te].to_numpy(), R.never[te].to_numpy()), 2 + np.exp(p[2])); c68[te], c95[te] = a, b
out += ["", "## Recalibrated interval M1 (NOT shipped), cross-fitted on held-out element groups", "", "| stratum | rows (nuclei) | 68 % | 95 % |", "|---|---|---|---|"]
for nm, m in (("never-seen", (R.never == 1).to_numpy()), ("seen", (R.never == 0).to_numpy())):
    out.append(f"| {nm} | {int(m.sum())} ({R.nid[m].nunique()}) | {100 * c68[m].mean():.1f} | {100 * c95[m].mean():.1f} |")
# the interval that SHIPS: frozen v1 (frozen_np.json sigma_params: Student-t, width sig0(dE))
pf = np.array(P["frozen_sigma_params"]); nuf = 2 + np.exp(pf[2])
a1, b1 = cover(F.err_pick.to_numpy(), sig0(pf, F.dE.to_numpy()), nuf)
V = R[(R.grp == 5) & (R.never == 1)]; av, bv = cover(V.e.to_numpy(), sig0(pf, V.dE.to_numpy()), nuf)
out += ["", "## The SHIPPED interval (frozen v1) on data it never saw", "", "| set | records (nuclei) | 68 % | 95 % |", "|---|---|---|---|",
        f"| vault (element-grouped, one read) | {len(V)} ({V.nid.nunique()}) | {100 * av.mean():.1f} | {100 * bv.mean():.1f} |"]
for nm, m in (("fresh records, all", np.ones(len(F), bool)), ("fresh, nuclei never seen by the correction", F.never_seen.to_numpy()), ("fresh, 9 nuclei never touched anywhere", F.nuclide_clean.to_numpy())):
    out.append(f"| {nm} | {int(m.sum())} ({F.nid[m].nunique()}) | {100 * a1[m].mean():.1f} | {100 * b1[m].mean():.1f} |")
p, nu = np.array(P["M1_params"]), P["M1_nu"]; a, b = cover(F.err_pick.to_numpy(), sigma(p, F.dE.to_numpy(), F.never_seen.astype(float).to_numpy()), nu)
out += ["", "## Recalibrated interval M1 (NOT shipped) on the fresh records (descriptive)", "", "| subset | records (nuclei) | 68 % | 95 % |", "|---|---|---|---|"]
for nm, m in (("never seen by the model", F.never_seen.to_numpy()), ("9 nuclei never touched anywhere", F.nuclide_clean.to_numpy())):
    out.append(f"| {nm} | {int(m.sum())} ({F.nid[m].nunique()}) | {100 * a[m].mean():.1f} | {100 * b[m].mean():.1f} |")
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
