#!/usr/bin/env python3
"""README "Nuclei with no structure data": how many library nuclei have none, and the out-of-fold coverage of their interval.
Interval (CAPFAR): sigma = sqrt(sp^2 + s0^2) x conformal q per band (< / >= 100 keV); sp = sd of log10 capture over the 8 STRIP
engine models; fitted on the shipped no-structure value's STRIP error (the recipe run with our E1 constant), leave-one-DEV-fold-out (folds 0-5, Z <= 82).
    python scripts/release/score_nostruct.py docs/release/exam OUT.md
Ported from the development tree: scripts/release/terra/capture_farfield.py section 4 and scripts/release/extrap_sigma.py (fit, conformal, half_width)."""
import sys
import numpy as np, pandas as pd

D = sys.argv[1]; X = pd.read_parquet(D + "/capture_blind_cells.parquet"); F = pd.read_parquet(D + "/structure_flags.parquet")
M = ["s8l1", "s8l2", "s8l5", "s8l7", "s9l1", "s9l2", "s9l5", "s9l7"]


def conformal(r, lev):
    n = len(r); return float(np.quantile(r, min(1.0, np.ceil((n + 1) * lev) / n)))


def fit(e, sp, lo, s0_grid=np.arange(0.0, 0.205, 0.01)):
    best = None
    for s0 in s0_grid:
        s = np.sqrt(sp ** 2 + s0 ** 2); w = 0
        for b in (lo, ~lo): w += np.median(conformal(np.abs(e[b]) / s[b], 0.68) * s[b]) * b.sum()
        if best is None or w < best[0]: best = (w, s0)
    s0 = best[1]; s = np.sqrt(sp ** 2 + s0 ** 2)
    return dict(s0=float(s0), **{k: [conformal(np.abs(e[b]) / s[b], 0.68), conformal(np.abs(e[b]) / s[b], 0.95)] for k, b in (("q_lt100keV", lo), ("q_ge100keV", ~lo))})


def half_width(par, sp, energy_ev):
    s = np.sqrt(np.asarray(sp) ** 2 + par["s0"] ** 2); lo = np.asarray(energy_ev) < 1e5
    return (np.where(lo, par["q_lt100keV"][0], par["q_ge100keV"][0]) * s, np.where(lo, par["q_lt100keV"][1], par["q_ge100keV"][1]) * s)


L = np.stack([X[f"pred_strip_{m}"].to_numpy() for m in M]); e = X.pred_ours_strip.to_numpy() - X.target_log10.to_numpy()   # the shipped no-structure value: the recipe with our E1 constant
m = (X.Z.to_numpy() <= 82) & np.isin(X.fold, range(6)) & np.isfinite(e) & np.isfinite(X.pred_ours_strip.to_numpy()) & np.all(np.isfinite(L), 0)
ev, sp, Ev, fv = e[m], np.std(L[:, m], 0), X.energy_ev.to_numpy()[m], X.fold.to_numpy()[m]; lo = Ev < 1e5
h68, h95 = np.zeros(len(ev)), np.zeros(len(ev))
for k in range(6):
    te = fv == k; h68[te], h95[te] = half_width(fit(ev[~te], sp[~te], lo[~te]), sp[te], Ev[te])
a = np.abs(ev)
out = ["# Nuclei with no structure data (regenerated by scripts/release/score_nostruct.py)", "",
       f"library nuclei: {len(F)}; with no structure data: {int(F.nostruct.sum())}", "",
       "| interval | cells (nuclei) | 68 % coverage | 95 % coverage | median 68 % factor |", "|---|---|---|---|---|",
       f"| no-structure interval, out-of-fold (STRIP, DEV) | {int(m.sum())} ({X.nuclide_id[m].nunique()}) | {100 * np.mean(a < h68):.1f} | {100 * np.mean(a < h95):.1f} | x{10 ** np.median(h68):.2f} |"]
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
