#!/usr/bin/env python3
"""README "Retrodiction": ours (trained only on data up to year Y, Y = 2015..2023) vs our engine's TENDL no-data recipe,
scored on what was measured after Y; rows = the published 286 (curation rule P: model-derived / spectrum-averaged / summed
datasets removed; rows where TENDL-Y exists), 16 nuclei. Nucleus bootstrap 95 % CI, 5,000 draws, seed 20260910.
The comparison with the TENDL release of year Y (0.184) needs TENDL values we do not redistribute: see REPRODUCE.md.
    python scripts/release/score_retro.py docs/release/exam/retro_rows.parquet OUT.md
Ported from the development tree: audit2/rescore_c3_c6.py (C5) on release/retrain_clean/retro_rows_scored.parquet (clean arm)."""
import sys, numpy as np, pandas as pd
r = pd.read_parquet(sys.argv[1]); q = r[~r.P & np.isfinite(r.err_ours) & r.tendlY_available]
def rboot(nuc, a, b, seed=20260910, nb=5000):
    u, inv = np.unique(nuc, return_inverse=True); w = np.ones(len(a))
    sa, sb, sw = np.bincount(inv, w * a ** 2, len(u)), np.bincount(inv, w * b ** 2, len(u)), np.bincount(inv, w, len(u))
    c = np.random.default_rng(seed).multinomial(len(u), np.full(len(u), 1.0 / len(u)), size=nb).astype(float)
    dd = np.sqrt(c @ sa / (c @ sw)) - np.sqrt(c @ sb / (c @ sw)); lo, hi = np.percentile(dd, [2.5, 97.5])
    return np.sqrt(sa.sum() / sw.sum()), np.sqrt(sb.sum() / sw.sum()), lo, hi
a = rboot(q.nuclide_id.to_numpy(), q.err_ours.to_numpy(), q.err_recipe.to_numpy())
out = ["# Retrodiction (regenerated by scripts/release/score_retro.py)", "", "| rows (nuclei) | ours | TENDL no-data recipe (our engine) | ours - recipe [95 % CI] |", "|---|---|---|---|",
       f"| {len(q)} ({q.nuclide_id.nunique()}) | {a[0]:.4f} | {a[1]:.4f} | {a[0] - a[1]:+.4f} [{a[2]:+.4f}, {a[3]:+.4f}] |"]
open(sys.argv[2], "w").write("\n".join(out) + "\n"); print("\n".join(out))
