"""T2 structure: fixed-format readers, masses and separation energies, discrete levels and gamma
cascades, deformation, resonance data and nuclide bookkeeping, against TALYS (gate A-struct).

Two kinds of test:

* unit tests that need only TALYS's structure database (skipped without it), including a
  bit-exact check of the Duflo-Zuker port against the Fortran compiled from TALYS's own
  duflo.f90 with the TALYS build flags (the table below), and physical-value unit checks;
* acceptance tests against the reference dumps (skipped when absent): every number TALYS printed
  for structure is regenerated by the port and compared as TALYS formatted it -- discrete data
  must match character for character, numbers to the printed precision (A-struct: 1e-5).

Reference sources, in order: the extracted-directory tree named by $INCOGNITA_HF_STRUCT_EXTRACT
(``<variant>__<target>/levels*.out`` ...), then the tarballs in
``physics.hf.reference.reference_dir() / "raw"``. One variant per target (structure does not
depend on the variant). Run ``python tests/hf/test_structure.py`` for the gate report.
"""

from __future__ import annotations

import os
import re
import sys
import tarfile
from functools import cache
from pathlib import Path

import numpy as np
import pytest

from physics.hf.structure import files as F

STRUCTURE = Path(os.environ.get("TALYS_DIR", Path.home() / "opt/talys-src")) / "structure"
needs_db = pytest.mark.skipif(not STRUCTURE.is_dir(), reason="TALYS structure database absent")

# Duflo-Zuker mass excesses [MeV] from TALYS's duflo.f90 compiled with gfortran
# -O3 -ffp-contract=off (the TALYS build flags), printed es20.10: (N, Z, exc)
DUFLO_FORTRAN = [
    (4, 8, 3.2862808228e01),
    (9, 8, -1.8619995117e00),
    (14, 8, 1.0369537354e01),
    (30, 28, -6.1698883057e01),
]


# ------------------------------------------------------------------------------------------------
# unit tests (no dumps)
# ------------------------------------------------------------------------------------------------


def test_fortran_read_blank_null_implied_decimal_and_groups():
    assert F.fortran_read("  28  58  10   S   D", "(4x, 2i4, 2(3x, a1))") == [58, 10, "S", "D"]
    # blank fields read as zero, short records are blank padded
    assert F.fortran_read("   1", "(i4, f8.3, e10.3)") == [1, 0.0, 0.0]
    # no decimal point: the edit descriptor's d applies
    assert F.fortran_read(" 1454210", "(f8.6)") == [1.45421]
    # embedded blanks are ignored (BLANK='NULL')
    assert F.fortran_read(" 1 2", "(i4)") == [12]
    assert F.fortran_read("6.520E-13 ", "(e10.3)") == [6.52e-13]


@needs_db
def test_duflo_bit_exact_against_compiled_talys():
    from physics.hf.structure.masses import duflo

    for n, z, exc in DUFLO_FORTRAN:
        assert np.float32(duflo(n, z)) == np.float32(exc), (n, z)


@needs_db
def test_units_against_known_physical_values():
    from physics.hf.input.defaults import default_options
    from physics.hf.structure.masses import masses
    from physics.hf.structure.resonances import resonance_parameters

    o = default_options(28, 58)
    m = masses(o)
    Zix, Nix = m.index(28, 58)
    assert float(m.mass_amu[Zix, Nix]) == pytest.approx(57.935342, abs=1e-6)  # AME2020, amu
    # Ni-59 neutron separation energy = Q(n,gamma) of Ni-58, 8.999 MeV
    assert float(m.s_mev[0, 0, 1]) == pytest.approx(8.9993, abs=1e-3)
    r = resonance_parameters(28, 59, o)
    assert r.d0_ev == pytest.approx(13400.0)  # 13.4 keV s-wave spacing, in eV
    assert r.s0 == pytest.approx(3.2, rel=1e-6)  # S0 = 3.2e-4, stored in units of 1e-4
    au = resonance_parameters(79, 198)
    # Au-197 + n <Gamma_gamma> is ~0.124 eV: the file (and TALYS's variable) holds keV
    assert au.gamgam_ev == pytest.approx(0.128, rel=1e-5)
    assert au.gamgam_talys == pytest.approx(1.28e-4, rel=1e-5)
    # Nrr is read from columns 133-136: "  151" -> 15 (reproduced TALYS quirk)
    assert au.nrr == 15


@needs_db
def test_masses_match_the_pre_vectorisation_capture():
    """SPEED2 turned masses()'s grid loops into numpy array operations (the same float64
    operations per cell), parses each mass table once and memoises Duflo-Zuker. The fixture
    holds every output array of the cell-by-cell code for five runs: Fe-56 and Pb-208 defaults,
    U-238 + p with FRDM, O-16 + alpha with massmodel 0 and no experimental masses (Duflo-Zuker
    everywhere), Zr-90 with HFB-D1M and user massnucleus/massexcess/beta2. Bit-identical."""
    import torch

    from physics.hf.input.defaults import PARAM_SPECS, default_options, default_params
    from physics.hf.structure.masses import masses

    z = np.load(Path(__file__).parent / "fixtures" / "masses_speed2.npz")
    cases = [
        (26, 56, "n", {}, False),
        (82, 208, "n", {}, False),
        (92, 238, "p", {"massmodel": 1}, False),
        (8, 16, "a", {"massmodel": 0, "expmass": "n"}, False),
        (40, 90, "n", {"massmodel": 3}, True),
    ]
    for i, (Z, A, proj, over, edit) in enumerate(cases):
        o = default_options(Z, A, proj, over)
        p = default_params(Z, A, o)
        if edit:
            for key, val in (("massnucleus", A + 0.0123), ("massexcess", -7.5)):
                off = PARAM_SPECS[key].offsets
                p[key][off[0] + 1, off[1] + 2] = val
                p[key][off[0] + 3, off[1]] = val * 1.1
            off = PARAM_SPECS["beta2"].offsets
            p["beta2"][off[0], off[1] + 1, off[2]] = 0.31
        m = masses(o, p)
        assert m.flagduflo == bool(z[f"m{i}_flagduflo"]), i
        for name, v in vars(m).items():
            if isinstance(v, torch.Tensor):
                assert np.array_equal(v.numpy(), z[f"m{i}_{name}"]), (i, name)


@needs_db
def test_default_levels_for_a_nucleus_without_file_block():
    from physics.hf.input.defaults import default_options
    from physics.hf.structure.levels import discrete_levels

    o = default_options(28, 58)
    lv = discrete_levels(28, 45, o)  # far off stability: no block in Ni.lev
    assert lv.nlev == 1 and lv.nlevmax2 == 1
    assert float(lv.e_mev[1]) == pytest.approx(26.0 / 45, rel=1e-6)
    assert float(lv.spin[1]) == float(lv.spin[0]) + 2.0
    assert lv.branch_to[1, 0] == 0 and float(lv.branch_ratio[1, 0]) == 1.0


# ------------------------------------------------------------------------------------------------
# reference dumps
# ------------------------------------------------------------------------------------------------


def _extract_roots() -> list[Path]:
    env = os.environ.get("INCOGNITA_HF_STRUCT_EXTRACT")
    return [Path(p) for p in env.split(os.pathsep)] if env else []


@cache
def _sources() -> dict[str, tuple[str, object]]:
    """target tag -> (variant, loader(name_regex) -> {filename: text})"""
    out: dict[str, tuple[str, object]] = {}
    pref = {"default": 0, "wfc_off": 1}
    for root in _extract_roots():
        for d in sorted(root.glob("*__*")):
            if not d.is_dir():
                continue
            variant, tag = d.name.split("__", 1)
            if variant not in pref:
                continue
            if tag in out and pref[out[tag][0]] <= pref[variant]:
                continue

            def load(rx, d=d):
                r = re.compile(rx)
                return {p.name: p.read_text() for p in d.iterdir() if r.fullmatch(p.name)}

            out[tag] = (variant, load)
    try:
        from physics.hf import reference as ref

        raw = ref.reference_dir() / "raw"
    except Exception:  # pragma: no cover
        raw = None
    if raw is not None and raw.is_dir():
        for tgz in sorted(raw.glob("*__*.tar.gz")):
            if tgz.stat().st_size == 0 or tgz.name.startswith("FAILED"):
                continue
            variant, tag = tgz.name[: -len(".tar.gz")].split("__", 1)
            if variant not in pref or (tag in out and pref[out[tag][0]] <= pref[variant]):
                continue

            def load(rx, tgz=tgz):
                r = re.compile(rx)
                got = {}
                with tarfile.open(tgz) as tf:
                    for mem in tf:
                        name = mem.name.rsplit("/", 1)[-1]
                        if mem.isfile() and r.fullmatch(name):
                            got[name] = tf.extractfile(mem).read().decode("latin-1")
                return got

            out[tag] = (variant, load)
    return out


def _targets() -> list[str]:
    return sorted(_sources()) if STRUCTURE.is_dir() else []


needs_dumps = pytest.mark.skipif(not _targets(), reason="reference dumps not available")


def _target_za(tag: str) -> tuple[int, int]:
    from physics.hf.core.constants import NUC

    sym = re.match(r"[A-Za-z]+", tag).group(0)
    Z = [s.strip().lower() for s in NUC].index(sym.lower()) + 1
    return Z, int(tag[len(sym) :])


def _meta(text: str) -> dict[str, str]:
    out = {}
    for line in text.splitlines():
        if line.startswith("#") and not line.startswith("##") and ":" in line:
            k, _, v = line[1:].partition(":")
            if v.strip():
                out.setdefault(k.strip(), v.strip())
    return out


def _rows(text: str) -> list[str]:
    return [ln for ln in text.splitlines() if ln and not ln.startswith("#")]


def _es(x: float, w: int = 15) -> str:
    return f"{float(np.float32(x)):{w}.6E}"


@cache
def _setup(tag: str):
    from physics.hf.input.defaults import default_options
    from physics.hf.structure.masses import masses

    Z, A = _target_za(tag)
    o = default_options(Z, A)
    return o, masses(o)


def _render_levels(lv) -> list[str]:
    """levelsout.f90 write statements."""
    f = np.float32
    lines = []
    cpar = {-1: "-", 0: " ", 1: "+"}
    for i in range(lv.nlev + 1):
        tr = float(lv.half_life_ripl_s[i])
        taus = f"{float(f(tr)):15.6E}" if tr != 0.0 else " " * 15
        lines.append(
            f"{int(lv.levnum[i]):6d}{'':9}{float(f(lv.e_mev[i])):15.6E}{'':7}"
            f"{float(lv.spin[i]):4.1f}{'':13}{cpar[int(lv.parity[i])]}{'':9}"
            f"{int(lv.nbranch[i]):6d}{'':51}{taus}{'':6}{lv.assign[i]} {lv.ensdf[i]}"
        )
        for k in range(int(lv.nbranch[i])):
            pct = float(f(lv.branch_ratio[i, k]) * f(100.0))
            lines.append(
                f"{'':75}--->{int(lv.branch_to[i, k]):6d}{'':9}{pct:8.4f}{'':4}"
                f"{float(f(lv.conversion[i, k])):15.6E}{'':26}{lv.branch_assign[i][k]}"
            )
    return [ln.rstrip() for ln in lines]


@cache
def _populations(tag: str):
    """(energies, populated(Zcomp, Ncomp, E), flagpop) from TALYS's own talys.out record of
    which compound nuclei multiple emission processed at each incident energy."""
    o, _ = _setup(tag)
    _, load = _sources()[tag]
    texts = load(r"populations\.txt|talys_head\.out|talys\.out")
    if "talys.out" in texts:
        body = head = texts["talys.out"]
    elif "populations.txt" in texts:
        body, head = texts["populations.txt"], texts.get("talys_head.out", "")
    else:
        return None
    mm = re.search(r"^\s*outpopulation\s+([yn])\s+flagpop", head, re.M)
    if mm is None:
        return None
    flagpop = mm.group(1) == "y"
    energies, pop, cur = [], {}, None
    for line in body.splitlines():
        e = re.search(r"RESULTS FOR E=\s*([\d.Ee+-]+)", line)
        if e:
            cur = float(e.group(1))
            energies.append(cur)
            pop.setdefault(cur, set())
            continue
        p = re.search(r"Population of Z=\s*(\d+) N=\s*(\d+)", line)
        if p and cur is not None:
            Z, N = int(p.group(1)), int(p.group(2))
            pop[cur].add((o.Zinit - Z, o.Ninit - N))
    if not energies:
        return None

    def populated(zc: int, nc: int, e: float) -> bool:
        return (zc, nc) in pop.get(e, ())

    return tuple(energies), populated, flagpop


def gate_levels_and_masses(tag: str) -> dict:
    """Compare every levels*.out and gamma*.tot of one target: counts and relative errors."""
    from physics.hf.input.nuclides import structure_history
    from physics.hf.structure.levels import discrete_levels, gamma_cascade

    o, m = _setup(tag)
    variant, load = _sources()[tag]
    lev_files = load(r"levels\d{6}\.out")
    gam_files = load(r"gamma\d{6}\.tot")
    pops = _populations(tag)
    if pops is None:
        pytest.skip(f"{tag}: no talys.out population record to replay the call sequence")
    energies, populated, flagpop = pops
    hist = structure_history(o, energies, populated, m, flagpop)
    prior, prior_s = hist.prior_call, hist.prior_call_at_structure
    res = {
        "files": 0,
        "lines": 0,
        "line_mismatch": [],
        "num_rel": [],
        "num_mismatch": [],
        "gamma_lines": 0,
        "gamma_mismatch": [],
    }
    for name, text in sorted(lev_files.items()):
        Z, A = int(name[6:9]), int(name[9:12])
        lv = discrete_levels(Z, A, o, m, prior_call=(o.Zinit - Z, o.Ninit - (A - Z)) in prior)
        want = [ln.rstrip() for ln in _rows(text)]
        got = _render_levels(lv)
        res["files"] += 1
        res["lines"] += len(want)
        if len(want) != len(got):
            res["line_mismatch"].append((name, "count", len(want), len(got)))
        for a, b in zip(want, got, strict=False):
            if a != b:
                res["line_mismatch"].append((name, a, b))
        meta = _meta(text)
        Zix, Nix = o.Zinit - Z, o.Ninit - (A - Z)
        port = {
            "nuclear mass [amu]": float(m.mass_amu[Zix, Nix]),
            "neutron separation energy [MeV]": float(m.s_mev[Zix, Nix, 1]),
            "proton separation energy [MeV]": float(m.s_mev[Zix, Nix, 2]),
            "alpha separation energy [MeV]": float(m.s_mev[Zix, Nix, 6]),
        }
        for k, v in port.items():
            t = float(meta[k])
            if f"{v:13.6E}".strip() != meta[k]:
                res["num_mismatch"].append((name, k, meta[k], f"{v:13.6E}"))
            if t != 0.0:
                res["num_rel"].append(abs(v / t - 1.0))
        if int(meta["number of excited levels"]) != lv.nlev:
            res["num_mismatch"].append((name, "nlev", meta["number of excited levels"], lv.nlev))
        gname = f"gamma{name[6:12]}.tot"
        if gname in gam_files:
            zn = (o.Zinit - Z, o.Ninit - (A - Z))
            if (zn in prior) != (zn in prior_s):  # gamma*.tot was written at structure time
                lv = discrete_levels(Z, A, o, m, prior_call=zn in prior_s)
            gwant = [ln.rstrip() for ln in _rows(gam_files[gname])]
            ggot = []
            for g in gamma_cascade(lv, o.flagelectron):
                ggot.append(
                    f"{g['level']:6d}{'':9}{_es(g['e_mev'])}{len(g['lines']):6d}{'':9}"
                    f"{_es(g['yield'])}".rstrip()
                )
                for p, d, eg, br, pe, de in g["lines"]:
                    ggot.append(
                        f"{'':60}{p:6d}{'':9}{d:6d}{'':9}{_es(eg)}{_es(br)}{_es(pe)}"
                        f"{_es(de)}".rstrip()
                    )
            res["gamma_lines"] += len(gwant)
            for a, b in zip(gwant, ggot, strict=False):
                if a != b:
                    res["gamma_mismatch"].append((gname, a, b))
            if len(gwant) != len(ggot):
                res["gamma_mismatch"].append((gname, "count", len(gwant), len(ggot)))
    return res


def gate_deformation(tag: str) -> dict:
    from physics.hf.input.nuclides import weak_coupling_core
    from physics.hf.structure.deformation import deformation, weak_coupling
    from physics.hf.structure.levels import discrete_levels

    o, m = _setup(tag)
    _, load = _sources()[tag]
    Z, A = o.Ztarget, o.Atarget
    lv = discrete_levels(Z, A, o, m)
    d = deformation(Z, A, o, lv, m)
    if A % 2 == 1:  # nuclides.f90:227
        zc, nc = weak_coupling_core(o)
        cz, ca = o.Zinit - zc, o.Zinit - zc + o.Ninit - nc
        clv = discrete_levels(cz, ca, o, m)
        d = weak_coupling(d, lv, deformation(cz, ca, o, clv, m), clv, o)
    res = {"rows": 0, "mismatch": []}
    seen = set()
    for name, text in sorted(load(r"directE\d{4}\.\d{3}\.out").items()):
        for ln in _rows(text):
            parts = ln.split()
            if len(parts) < 8:
                continue
            lev, dtype, dpar = int(parts[0]), parts[6], parts[7]
            if lev in seen:
                continue
            seen.add(lev)
            res["rows"] += 1
            got = f"{float(np.float32(d.deform[lev])):.6E}"
            if dtype != d.deftype or got != dpar:
                res["mismatch"].append((name, lev, dtype, dpar, d.deftype, got))
    return res


def gate_resonances(tag: str) -> dict:
    from physics.hf.structure.resonances import resonance_parameters

    o, _ = _setup(tag)
    _, load = _sources()[tag]
    res = {"values": 0, "mismatch": []}
    checks = {
        "experimental D0 [eV]": "d0_ev",
        "experimental D0 unc. [eV]": "dd0_ev",
        "global D0 [eV]": "d0global_ev",
        "experimental D1 [eV]": "d1_ev",
        "experimental D1 unc. [eV]": "dd1_ev",
    }
    for name, text in sorted(load(r"ld\d{6}\.gs").items()):
        Z, A = int(name[2:5]), int(name[5:8])
        r = resonance_parameters(Z, A, o)
        meta = _meta(text)
        for key, attr in checks.items():
            if key in meta:
                res["values"] += 1
                got = f"{float(np.float32(getattr(r, attr))):13.6E}".strip()
                if got != meta[key]:
                    res["mismatch"].append((name, key, meta[key], got))
    for name, text in sorted(load(r"psf\d{6}\.E1").items()):
        Z, A = int(name[3:6]), int(name[6:9])
        r = resonance_parameters(Z, A, o)
        meta = _meta(text)
        for key, val in (
            ("experimental Gamma_gamma [eV]", r.gamgam_talys),
            ("experimental Gamma_gamma unc. [eV]", r.dgamgam_talys),
        ):
            if key in meta:
                res["values"] += 1
                got = f"{float(np.float32(val)):13.6E}".strip()
                if got != meta[key]:
                    res["mismatch"].append((name, key, meta[key], got))
    return res


def gate_talys_out(tag: str) -> dict:
    from physics.hf.input.nuclides import q_values

    o, m = _setup(tag)
    _, load = _sources()[tag]
    texts = load(r"talys(_head)?\.out")
    text = texts.get("talys_head.out") or texts.get("talys.out") or ""
    res = {"values": 0, "mismatch": []}
    q = q_values(m, o)
    syms = "gnpdtha"
    for t in range(7):
        mm = re.search(rf"Q\(n,{syms[t]}\):\s*(-?[\d.]+)", text)
        if mm:
            res["values"] += 1
            got = f"{q[t]:8.5f}".strip()
            if got != mm.group(1):
                res["mismatch"].append(("Q", syms[t], mm.group(1), got))
    mm = re.search(r"Target\s+:\s+\S+\s+Mass in a\.m\.u\.\s+:\s+([\d.]+)", text)
    if mm:
        res["values"] += 1
        tz, tn = 0, 1
        got = f"{float(m.mass_amu[tz, tn]):.6f}"
        if got != mm.group(1):
            res["mismatch"].append(("target mass", mm.group(1), got))
    return res


def gate_nuclides(tag: str) -> dict:
    """Nuclei with structure: TALYS's level files vs (a) the port's call-sequence replay driven by
    TALYS's own populations (bookkeeping exact?) and (b) the port's energy-bound estimate."""
    from physics.hf.input.nuclides import residual_nuclei, structure_history

    o, m = _setup(tag)
    _, load = _sources()[tag]
    have = set()
    for name in load(r"levels\d{6}\.out"):
        Z, A = int(name[6:9]), int(name[9:12])
        have.add((o.Zinit - Z, o.Ninit - (A - Z)))
    pops = _populations(tag)
    replay = set()
    if pops is not None:
        replay = set(structure_history(o, pops[0], pops[1], m, pops[2]).order)
    energies = pops[0] if pops is not None else (20.0,)
    est = set(residual_nuclei(o.Ztarget, o.Atarget, energies, o, m))
    return {
        "dump": len(have),
        "replay_missing": sorted(have - replay) if pops else None,
        "replay_extra": sorted(replay - have) if pops else None,
        "estimate": len(est),
        "missing": sorted(have - est),
        "extra": sorted(est - have),
    }


@needs_dumps
@pytest.mark.parametrize("tag", _targets())
def test_levels_and_masses_match_talys(tag):
    r = gate_levels_and_masses(tag)
    assert r["files"] > 0
    assert not r["line_mismatch"], r["line_mismatch"][:5]
    assert not r["num_mismatch"], r["num_mismatch"][:5]
    assert not r["gamma_mismatch"], r["gamma_mismatch"][:5]
    assert max(r["num_rel"], default=0.0) <= 1e-5


@needs_dumps
@pytest.mark.parametrize("tag", _targets())
def test_deformation_matches_talys(tag):
    r = gate_deformation(tag)
    assert not r["mismatch"], r["mismatch"][:5]


@needs_dumps
@pytest.mark.parametrize("tag", _targets())
def test_resonance_data_matches_talys(tag):
    r = gate_resonances(tag)
    assert not r["mismatch"], r["mismatch"][:5]


@needs_dumps
@pytest.mark.parametrize("tag", _targets())
def test_q_values_and_target_mass_match_talys(tag):
    r = gate_talys_out(tag)
    assert not r["mismatch"], r["mismatch"]


@needs_dumps
@pytest.mark.parametrize("tag", _targets())
def test_residual_nuclei_cover_talys(tag):
    r = gate_nuclides(tag)
    # the call-sequence replay on TALYS's populations reproduces exactly the nuclei TALYS built
    if r["replay_missing"] is not None:
        assert not r["replay_missing"] and not r["replay_extra"], r
    # the energy-bound estimate is a superset of them
    assert not r["missing"], r


def main() -> int:
    tags = _targets()
    if not tags:
        print("no reference dumps found")
        return 1
    tot = {
        "files": 0,
        "lines": 0,
        "lm": 0,
        "gl": 0,
        "gm": 0,
        "nm": 0,
        "rel": [],
        "dr": 0,
        "dm": 0,
        "rv": 0,
        "rm": 0,
        "qv": 0,
        "qm": 0,
        "nuc_missing": 0,
        "nuc_extra": 0,
    }
    for tag in tags:
        a = gate_levels_and_masses(tag)
        d = gate_deformation(tag)
        r = gate_resonances(tag)
        q = gate_talys_out(tag)
        n = gate_nuclides(tag)
        tot["files"] += a["files"]
        tot["lines"] += a["lines"]
        tot["lm"] += len(a["line_mismatch"])
        tot["gl"] += a["gamma_lines"]
        tot["gm"] += len(a["gamma_mismatch"])
        tot["nm"] += len(a["num_mismatch"])
        tot["rel"] += a["num_rel"]
        tot["dr"] += d["rows"]
        tot["dm"] += len(d["mismatch"])
        tot["rv"] += r["values"]
        tot["rm"] += len(r["mismatch"])
        tot["qv"] += q["values"]
        tot["qm"] += len(q["mismatch"])
        tot["nuc_missing"] += len(n["missing"])
        tot["nuc_extra"] += len(n["extra"])
        print(
            f"{tag}: levels files {a['files']} lines {a['lines']} mism {len(a['line_mismatch'])}"
            f" | gamma {a['gamma_lines']} mism {len(a['gamma_mismatch'])}"
            f" | mass/S mism {len(a['num_mismatch'])}"
            f" | deform {d['rows']} mism {len(d['mismatch'])}"
            f" | res {r['values']} mism {len(r['mismatch'])}"
            f" | Q {q['values']} mism {len(q['mismatch'])}"
            f" | nuclides dump {n['dump']} replay miss/extra {n['replay_missing']}/"
            f"{n['replay_extra']} estimate {n['estimate']} missing {n['missing']}"
        )
        for lst in (
            a["line_mismatch"][:2],
            a["gamma_mismatch"][:2],
            a["num_mismatch"][:2],
            d["mismatch"][:2],
            r["mismatch"][:2],
            q["mismatch"][:2],
        ):
            for x in lst:
                print("   ", x)
    rel = np.array(tot["rel"]) if tot["rel"] else np.zeros(1)
    print("\nA-struct:", {k: v for k, v in tot.items() if k != "rel"})
    print(
        f"mass/S |rel| median {np.median(rel):.2e} p95 {np.percentile(rel, 95):.2e} "
        f"max {rel.max():.2e} over {len(tot['rel'])} values"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
