"""T3: TALYS defaults (physics/hf/input/defaults.py) against TALYS's own echo of what it resolved.

Reference. TALYS prints every resolved global switch in talys.out ("USER INPUT FILE + DEFAULTS",
inputout.f90) and, with `partable y`, every adjustable parameter per nucleus (partable.f90) plus
the general ones at the end of a run (finalout.f90). The cases are a 1 MeV run of each of the 24
reference targets, the same targets on a two-energy grid (so the structure-dependent onsets
print as numbers), and explicit-keyword cases chosen to exercise each dependent default: the
`ldmodel 1` actinide trap, `strength 8`, `ldmodel 2/5`, `micro y`, `endf y`, `astro y`,
`massdis y`, `soukho y`, `colenhance y`, `widthmode 0`, `widthfluc y`, `preequilibrium n`, OMP
geometry links and global level-density keywords, and proton and alpha projectiles.

Data. The raw runs live in features/hf_reference/t3_echo/<case>/ (talys.inp, talys_head.out,
parameters.dat), produced on a second machine with TALYS built from the same source as the first
(input_*.f90 md5-identical). Every case's input is recorded in the fixture, so the runs can be
regenerated by feeding `inp` (plus `energies` when present) to any TALYS 2.x binary with
`partable y`. The committed fixture tests/hf/fixtures/t3_defaults_echo.json.gz holds the parsed
echoes, the general parameters and the per-nucleus parameters of a subset, so these tests run
without the raw directory; rebuild it with

    uv run python -m tests.hf.test_defaults build-fixture
"""

from __future__ import annotations

import gzip
import json
import os
import sys
from pathlib import Path

import pytest
import torch

from physics.hf.input import defaults as D

ROOT = Path(__file__).resolve().parents[2]
RAW = Path(os.environ.get("INCOGNITA_T3_ECHO_RAW", ROOT / "features" / "hf_reference" / "t3_echo"))
FIXTURE = Path(__file__).parent / "fixtures" / "t3_defaults_echo.json.gz"

SYMBOL_Z = {
    "Ca": 20, "Fe": 26, "Co": 27, "Ni": 28, "Zr": 40, "Nb": 41, "Mo": 42, "Sn": 50, "I": 53,
    "Ba": 56, "Ce": 58, "Au": 79, "Pb": 82, "Bi": 83, "Nd": 60, "Sm": 62, "Gd": 64, "Er": 68,
    "W": 74, "Th": 90, "U": 92, "Pu": 94, "Am": 95,
}  # fmt: skip
# per-nucleus parameters.dat rows are kept in the fixture only for these cases (size)
PARTABLE_CASES = (
    "default__Fe056", "default__Sm152", "default__U238", "default__Am241", "ldmodel1__U238",
    "ldmodel1__Th232", "strength8__Au197", "ldmodel2__Zr090", "ldmodel5__Sm152", "alpha__Bi209",
    "proton__Ni058", "alphald__Fe056", "rvadjust__Fe056",
)  # fmt: skip
UPBEND = {
    "upbendc": ("upbend", 1), "upbende": ("upbend", 2), "upbendf": ("upbend", 3),
    "upbendcadjust": ("upbendadjust", 1), "upbendeadjust": ("upbendadjust", 2),
    "upbendfadjust": ("upbendadjust", 3),
}  # fmt: skip
# general-block keywords that are Options, not Params
GENERAL_OPTIONS = {
    "ldmodel": "ldmodelCN", "colenhance": "flagcolall", "strength": "strength",
    "strengthM1": "strengthM1", "fismodel": "fismodel", "deuteronomp": "deuteronomp",
    "alphaomp": "alphaomp",
}  # fmt: skip
# general-block keywords that hold the (0,0) entry of a per-nucleus parameter
GENERAL_CN_ENTRY = {"alphald", "betald", "gammashell1", "pshiftconstant"}


# ---------------------------------------------------------------------------------------------
# fixture: build from the raw runs, load in tests
# ---------------------------------------------------------------------------------------------


def _read_inp(text: str) -> dict[str, str]:
    return dict(line.split(None, 1) for line in text.splitlines() if line.strip())


def build_fixture(raw: Path = RAW, out: Path = FIXTURE) -> dict:
    cases = {}
    for d in sorted(p for p in raw.iterdir() if (p / "talys_head.out").exists()):
        echo = D.parse_talys_echo((d / "talys_head.out").read_text())
        pdat = (d / "parameters.dat").read_text() if (d / "parameters.dat").exists() else ""
        c = {
            "inp": _read_inp((d / "talys.inp").read_text()),
            "done": json.loads((d / "done.json").read_text()),
            "echo": {k: v for k, v in echo.items() if k not in D.ECHO_NOT_MODELLED},
            "general": D.parse_partable_general(pdat),
        }
        if d.name in PARTABLE_CASES:
            c["partable"] = D.parse_partable(pdat)
        cases[d.name] = c
    out.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(out, "wt") as f:
        json.dump(
            {"source": "features/hf_reference/t3_echo", "cases": cases}, f, separators=(",", ":")
        )
    return cases


def _cases() -> dict:
    if RAW.is_dir() and any(RAW.glob("*/talys_head.out")):
        cases = {}
        for d in sorted(p for p in RAW.iterdir() if (p / "talys_head.out").exists()):
            pdat = (d / "parameters.dat").read_text() if (d / "parameters.dat").exists() else ""
            cases[d.name] = {
                "inp": _read_inp((d / "talys.inp").read_text()),
                "echo": D.parse_talys_echo((d / "talys_head.out").read_text()),
                "general": D.parse_partable_general(pdat),
                "partable": D.parse_partable(pdat),
            }
        return cases
    if FIXTURE.exists():
        with gzip.open(FIXTURE, "rt") as f:
            return json.load(f)["cases"]
    return {}


CASES = _cases()
needs_reference = pytest.mark.skipif(
    not CASES, reason="no TALYS defaults echo (raw dir or fixture)"
)


def _split_inp(inp: dict[str, str]):
    """(Z, A, projectile, energy, Options keywords, Params keyword forms) from a case input."""
    kv = dict(inp)
    proj, sym, A = kv.pop("projectile"), kv.pop("element").capitalize(), int(kv.pop("mass"))
    energy = kv.pop("energy")
    kv.pop("partable", None)
    opt = {k: v for k, v in kv.items() if k in D.OPTION_KEYWORDS}
    par = {k: v for k, v in kv.items() if k not in D.OPTION_KEYWORDS}
    return SYMBOL_Z[sym], A, proj, energy, opt, par


def _params_overrides(par: dict[str, str]) -> dict[str, object]:
    """Keyword forms from a case input -> default_params overrides (scalar or full tensor)."""
    ov: dict[str, object] = {}
    for k, v in par.items():
        spec = D.PARAM_SPECS[k.lower()]
        words = v.split()
        if len(words) == 1:
            ov[spec.keyword] = float(words[0])
        elif len(words) == 2 and words[0] in D.PARSYM and len(spec.dims) == 1:
            ov.setdefault(spec.keyword, {})[words[0]] = float(words[1])
        else:
            raise NotImplementedError(f"keyword form {k} {v}")
    return ov


def _structure_from_grid(cases: dict) -> dict[tuple[str, str], tuple[float, float]]:
    """(projectile, target tag) -> (S_projectile, epreeq) as TALYS printed them on the two-energy
    grid. Used to resolve the sentinels in the *other* runs of the same target."""
    out = {}
    for name, c in cases.items():
        if not name.startswith("grid") or c["inp"].get("endf") == "y":
            continue
        e = c["echo"]
        try:
            out[(c["inp"]["projectile"], name.split("__")[1])] = (
                float(e["widthfluc"]), float(e["preequilibrium"]),
            )  # fmt: skip
        except (KeyError, ValueError):
            continue
    return out


def _expected_for_case(name: str, c: dict, structure: dict):
    Z, A, proj, energy, opt, par = _split_inp(c["inp"])
    o = D.default_options(Z, A, proj, opt)
    st = structure.get((proj, name.split("__")[1]))
    e_inc = None
    if st is not None:
        o = D.resolve_structure_defaults(o, s_projectile_mev=st[0], e_last_level_mev=st[1])
    numeric_onsets = energy == "energies" or o.flagastro  # Ninc > 1 prints the onset energies
    if st is not None and not numeric_onsets:
        e_inc = float(energy)
    exp = D.echo_expected(o, e_inc)
    if st is not None and numeric_onsets:
        for key, f in (("widthfluc", "ewfc_mev"), ("preequilibrium", "epreeq_mev"),
                       ("multipreeq", "emulpre_mev")):  # fmt: skip
            exp[key] = getattr(o, f)
        exp["urr"] = o.eurr_mev if o.flagurr else "n"
    return o, exp, par


# ---------------------------------------------------------------------------------------------
# tests that need no reference data
# ---------------------------------------------------------------------------------------------


def test_ldmodel_absent_is_not_ldmodel_1_for_actinides():
    """The WP-24 trap: 'ldmodel 1' is the documented default but not the resolved one above
    A = 215 (input_densitymodel.f90:90), and the difference cascades."""
    absent = D.default_options(92, 238)
    pinned = D.default_options(92, 238, overrides={"ldmodel": 1})
    assert (absent.ldmodelall, absent.ldmodelCN, absent.flagparity) == (7, 7, True)
    assert (pinned.ldmodelall, pinned.ldmodelCN, pinned.flagparity) == (1, 1, False)
    assert not absent.is_explicit("ldmodel") and pinned.is_explicit("ldmodel")
    # the E1 wtable default reads ldmodel: no entry for 7, 1.048 for CTM with collective enhancement
    w_absent = D.default_params(92, 238, absent).at("wtable", 0, 0, 1, 1)
    w_pinned = D.default_params(92, 238, pinned).at("wtable", 0, 0, 1, 1)
    assert float(w_absent) == 1.0 and float(w_pinned) == pytest.approx(1.048)
    # and it is the actinide rule, not a global one
    assert (
        D.default_options(26, 56).ldmodelall
        == D.default_options(26, 56, overrides={"ldmodel": 1}).ldmodelall
    )


def test_true_defaults_for_a_neutron():
    o = D.default_options(26, 56)
    assert (o.strength, o.strengthM1, o.wmode, o.widthmode) == (9, 3, 1, 1)  # Moldauer, SMLO tables
    assert (o.preeqmode, o.mpreeqmode, o.alphaomp, o.deuteronomp) == (2, 2, 6, 4)
    assert not o.flagfission and o.flagsoukho and not o.flagriplomp and not o.flagspher
    assert (o.maxZ, o.maxN) == (12, 28)  # nuclides.f90:140-141: Ninit - 3 = 28
    assert o.ewfc_mev == -1.0 and o.epreeq_mev == -1.0  # sentinels until structure is read
    assert D.default_options(26, 56, "p").wmode == 2  # HRTW for charged projectiles
    u = D.default_options(92, 238)
    assert u.flagfission and u.flagcolall and u.riplomp[1] == 2408 and not u.flagsoukho
    pu = D.default_options(94, 239, overrides={"soukho": "y"})
    assert pu.flagsoukho and pu.riplomp[1] == 0 and pu.flagsoukhoinp


def test_explicit_widthfluc_y_does_not_move_the_neutron_onset():
    """`widthfluc y` sets ewfc = 10 only for k0 > 1 (input_compoundmodel.f90 keyword loop)."""
    assert D.default_options(26, 56, overrides={"widthfluc": "y"}).ewfc_mev == -1.0
    assert D.default_options(26, 56, "p", overrides={"widthfluc": "y"}).ewfc_mev == 10.0
    assert D.default_options(26, 56, overrides={"widthfluc": "n"}).ewfc_mev == 0.0
    assert (
        D.default_options(26, 56, overrides={"preequilibrium": "n"}).epreeq_mev == D.EMAXTALYS_MEV
    )


def test_structure_resolution():
    o = D.resolve_structure_defaults(
        D.default_options(26, 56), s_projectile_mev=11.197, e_last_level_mev=4.448
    )
    assert (o.ewfc_mev, o.epreeq_mev, o.eurr_mev) == (11.197, 4.448, -1.0)  # no URR without endf
    f = D.energy_flags(o, 1.0)
    assert f["flagwidth"] and not f["flagpreeq"] and not f["flagmulpre"] and not f["flaggiant"]
    endf = D.default_options(26, 56, overrides={"endf": "y"})
    assert endf.eninclow_mev == 0.0 and endf.flagurr and endf.flagchannels and endf.eadd_mev == 30.0
    # D0 of Fe-57 is 2.54e4 eV in structure/resonances/Fe.res; TALYS echoes elow 2.54E-02
    r = D.resolve_structure_defaults(
        endf, s_projectile_mev=11.197, e_last_level_mev=4.448, d0_ev=2.54e4
    )
    assert r.eninclow_mev == pytest.approx(2.54e-2) and r.eurr_mev == 11.197
    kept = D.resolve_structure_defaults(endf, s_projectile_mev=11.197, e_last_level_mev=4.448)
    assert kept.eninclow_mev == 0.0  # no D0 given: stays unresolved rather than guessed
    with pytest.raises(ValueError):
        D.energy_flags(D.default_options(26, 56), 1.0)


def test_params_index_convention_and_links():
    o = D.default_options(26, 56)
    p = D.default_params(26, 56, o)
    for k, spec in D.PARAM_SPECS.items():
        assert p[k].dtype == torch.float64 and tuple(p[k].shape) == spec.shape, k
    assert float(p.at("fiso", -1)) == -1.0  # (-1:numpar) array, shifted by one
    assert float(p.at("bdamp", 0, 0, 1)) == pytest.approx(0.01)  # 1-based barrier axis
    with pytest.raises(IndexError):
        p.at("bdamp", 0, 0, 0)
    assert float(p.at("ufermi", 3, 4, 0)) == 30.0 and float(p.at("ufermi", 3, 4, 2)) == 45.0
    assert float(p.at("rtransmom", 0, 0, 1)) == pytest.approx(0.6)
    assert p["M2constant"] is p["m2constant"]
    # rwadjust follows rvadjust unless given (input_omppar.f90:632); not for Avrigeanu alphas
    q = D.default_params(26, 56, o, overrides={"rvadjust": {"n": 1.1, "a": 1.2}, "cglobal": 2.0,
                                               "avdadjust": {"p": 0.9}})  # fmt: skip
    assert float(q.at("rwadjust", 1)) == pytest.approx(1.1) and float(q.at("rwadjust", 6)) == 1.0
    assert float(q.at("avdadjust", 2)) == pytest.approx(0.9) and float(q.at("avdadjust", 1)) == 1.0
    rv = torch.ones(7, dtype=torch.float64)
    rv[1] = 1.3
    assert float(
        D.default_params(26, 56, o, overrides={"rvadjust": rv}).at("rwadjust", 1)
    ) == pytest.approx(1.3)
    assert float(q.at("ctable", 5, 5, 0)) == 2.0
    q.requires_grad_(["aadjust"])
    assert q["aadjust"].requires_grad
    with pytest.raises(KeyError):
        D.default_params(26, 56, o, overrides={"not_a_keyword": 1.0})
    with pytest.raises(ValueError):
        D.default_params(92, 238, o)


def test_unknown_or_per_nucleus_keywords_are_refused():
    with pytest.raises(KeyError):
        D.default_options(26, 56, overrides={"aadjust": 1.1})  # a Params keyword
    with pytest.raises(ValueError):
        D.default_options(26, 56, overrides={"ldmodel": "26 56 2"})


# ---------------------------------------------------------------------------------------------
# tests against the TALYS echo
# ---------------------------------------------------------------------------------------------


@needs_reference
def test_reference_covers_every_target_and_the_cascades():
    names = set(CASES)
    assert sum(n.startswith("default__") for n in names) == 24
    assert sum(n.startswith("grid__") for n in names) == 24
    for n in ("ldmodel1__U238", "strength8__Au197", "micro__Co059", "endf__Fe056", "astro__Fe056",
              "massdis__U235", "soukho__Pu239", "proton__Ni058", "alpha__Bi209"):  # fmt: skip
        assert n in names, n


@needs_reference
@pytest.mark.parametrize("name", sorted(CASES))
def test_options_reproduce_the_talys_echo(name):
    c = CASES[name]
    structure = _structure_from_grid(CASES)
    o, exp, _ = _expected_for_case(name, c, structure)
    bad = D.compare_echo(exp, c["echo"])
    assert not bad, f"{name}: (expected, TALYS printed) {bad}"
    unmodelled = set(c["echo"]) - set(exp) - D.ECHO_NOT_MODELLED
    energy_keys = {"widthfluc", "urr", "preequilibrium", "multipreeq", "elow"}
    assert unmodelled <= energy_keys, (
        f"{name}: echo keys neither modelled nor excluded: {unmodelled}"
    )


@needs_reference
@pytest.mark.parametrize("name", sorted(n for n in CASES if CASES[n].get("general")))
def test_general_parameters(name):
    c = CASES[name]
    Z, A, proj, _, opt, par = _split_inp(c["inp"])
    o = D.default_options(Z, A, proj, opt)
    p = D.default_params(Z, A, o, _params_overrides(par))
    checked, bad = 0, []
    for key, particle, printed in c["general"]:
        k = key.lower()
        if key in GENERAL_OPTIONS:
            got = getattr(o, GENERAL_OPTIONS[key])
            want = ("y" if got else "n") if isinstance(got, bool) else str(got)
            ok = want == printed
        else:
            spec = D.PARAM_SPECS.get(k)
            if spec is None or spec.resolved_by:
                continue
            if particle is not None:
                val = p.at(k, D.PARSYM.index(particle))
            elif k in GENERAL_CN_ENTRY:
                val = p.at(k, 0, 0)
            else:
                val = p[k]
            want = float(val)
            ok = abs(want - float(printed)) <= 1e-5 + 1e-5 * abs(float(printed))
        checked += 1
        if not ok:
            bad.append((key, particle, want, printed))
    assert checked > 40
    assert not bad, f"{name}: (keyword, particle, ours, TALYS) {bad}"


@needs_reference
@pytest.mark.parametrize("name", sorted(n for n in CASES if CASES[n].get("partable")))
def test_per_nucleus_parameters(name):
    c = CASES[name]
    Z, A, proj, _, opt, par = _split_inp(c["inp"])
    o = D.default_options(Z, A, proj, opt)
    p = D.default_params(Z, A, o, _params_overrides(par))
    checked, bad = 0, []
    for key, z, a, printed, qual in c["partable"]:
        k, comp = UPBEND.get(key.lower(), (key.lower(), None))
        spec = D.PARAM_SPECS.get(k)
        if spec is None:
            continue
        zix, nix = o.Zinit - z, o.Ninit - (a - z)
        if spec.resolved_by and not (k in ("ctable", "ptable") and o.ldmodel_of(zix, nix) <= 3):
            continue
        q = qual.split()
        idx = [zix, nix]
        if len(spec.dims) == 3:
            idx.append(int(q[0]))
        elif len(spec.dims) >= 4:
            idx += [1 if q[0][0] == "E" else 0, int(q[0][1:])]
            if len(spec.dims) == 5:
                idx.append(comp if comp else (int(q[1]) if len(q) > 1 else 1))
        want = float(p.at(k, *idx))
        # f10.5 prints five decimals; es12.5 (upbend) six significant digits
        tol = 1e-5 * abs(printed) + (1e-15 if "upbend" in k else 6e-6)
        checked += 1
        if abs(want - printed) > tol:
            bad.append((key, z, a, qual, want, printed))
    assert checked > 100
    assert not bad, f"{name}: {len(bad)} mismatches, first {bad[:5]}"


if __name__ == "__main__":
    if sys.argv[1:] == ["build-fixture"]:
        cases = build_fixture()
        print(f"wrote {FIXTURE} ({FIXTURE.stat().st_size / 1024:.0f} KiB, {len(cases)} cases)")
    else:
        print(__doc__)
